---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================
- name: DCs AD data configuration
  hosts: dc01,dc02,dc03
  roles:
    - { role: 'ad', tags: 'ad_domain_data' }
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.hosts[dict_key].admin_password}}"
    domain_server: "{{lab.hosts[dict_key].hostname}}.{{domain}}"
    ad_users: "{{lab.domains[lab.hosts[dict_key].domain].users}}"
    ad_ou: "{{lab.domains[lab.hosts[dict_key].domain].organisation_units}}"
    ad_groups: "{{lab.domains[lab.hosts[dict_key].domain].groups}}"

- name: "Servers AD data configuration"
  hosts: srv01,srv03
  roles:
    - { role: 'settings/copy_files', tags: 'download_files' }
  vars:
    hostname: "{{lab.hosts[dict_key].hostname}}"
    domain_ou_path: "{{lab.hosts[dict_key].path}}"
