---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "{{domain_name}}/data/"
  tags: 'data'
# set AD trusts ==================================================================================================

- name: Trusts configuration
  hosts: dc01,dc03
  roles:
  - { role: 'dns_conditional_forwarder', tags: 'dns_conditional_forwarder' }
  - { role: 'trusts', tags: 'trust' }
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.hosts[dict_key].admin_password}}"
    remote_forest: "{{lab.domains[domain].trust}}"
    remote_admin: "Administrator@{{remote_forest}}"
    remote_admin_password: "{{lab.hosts[lab.domains[remote_forest].dc].admin_password}}"
    zone_name: "{{remote_forest}}"
    remote_dc: "{{lab.domains[remote_forest].dc}}"
    remote_dc_ip: "{{hostvars[groups[remote_dc][0]].ip}}"
