---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "{{domain_name}}/data/"
  tags: 'data'
# set AD datas ==================================================================================================

- name: ADCS
  hosts: srv03,dc01
  roles:
  - { role: 'adcs', tags: 'adcs'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.hosts[lab.domains[domain].dc].admin_password}}"
    ca_common_name: "{{lab.domains[domain].netbios_name}}-CA"

- name: ADCS
  hosts: dc03
  roles:
  - { role: 'adcs_templates', tags: 'adcs_templates'}
  vars:
    domain: "{{lab.hosts[dict_key].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.hosts[dict_key].admin_password}}"
    ca_common_name: "{{lab.domains[domain].netbios_name}}-CA"
    ca_host: "{{lab.domains[domain].ca_server}}"
