---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "{{domain_name}}/data/"
  tags: 'data'

- name: "Setup enable defender"
  hosts: dc01,dc03,srv03
  roles:
    - { role: 'settings/windows_defender', tags: 'windows_defender', windows_defender_status: 'on' }
#  vars:
#    script_path: "{{domain_name}}/scripts"

- name: Setup disable defender
  hosts: dc02,srv01
  roles:
    - { role: 'settings/windows_defender', tags: 'windows_defender', windows_defender_status: 'off' }
 # vars:
 #   script_path: "{{domain_name}}/scripts"
