---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "{{domain_name}}/data/"

# middle-earth.local
- name: "Setup vulnerabilities dc01"
  hosts: dc01
  roles:
#    - { role: 'vulns', tags: 'acl', ps_script: "{{script_path}}/acl.ps1"} # converted to json config and roles
  vars:
    script_path: "{{domain_name}}/scripts"

- name: "Setup vulnerabilities srv01"
  hosts: srv01
  roles:
  vars:
    script_path: "{{domain_name}}/scripts"

# eriador.middle-earth.local
- name: "Setup vulnerabilities dc02"
  hosts: dc02
  roles:
    - { role: "vulns/openshares", tags: 'openshares'}
    - { role: 'vulns', tags: 'asrep_roasting', ps_script: "{{script_path}}/asrep_roasting.ps1"}
    - { role: 'vulns', tags: 'constrained_delegation', ps_script: "{{script_path}}/constrained_delegation_use_any.ps1"}
    - { role: 'vulns', tags: 'ntlm_relay', ps_script: "{{script_path}}/ntlm_relay.ps1"}
    - { role: 'vulns', tags: 'responder', ps_script: "{{script_path}}/responder.ps1"}
#    - { role: 'vulns', tags: 'anonymous_ldap', ps_script: "{{script_path}}/anonymous_ldap.ps1"} # done with acl
#    - { role: 'vulns', tags: 'kerberoasting', ps_script: "{{script_path}}/kerberoasting.ps1"} # done by setting spn on user creation
#    - { role: 'vulns', tags: 'unconstrained_delegation', ps_script: "{{script_path}}/unconstrained_delegation.ps1"} # done with dc on forest to forest
#    - { role: 'vulns', tags: 'gpo_abuse', ps_script: "{{script_path}}/gpo_abuse.ps1"}
  vars:
    script_path: "{{domain_name}}/scripts"

- name: "Setup vulnerabilities srv02"
  hosts: srv02
  become: yes
  roles:
    - { role: 'vulns', tags: 'privesc_user', ps_script: "{{script_path}}/linux_privesc_user.sh"}
    - { role: 'vulns', tags: 'privesc_root', ps_script: "{{script_path}}/linux_privesc_root.sh"}
  vars:
    script_path: "{{domain_name}}/scripts"


# mordor.local
- name: "Setup vulnerabilities dc03"
  hosts: dc03
  roles:
    - { role: 'vulns/ntlmdowngrade', tags: 'ntlmdowngrade'}
  vars:
    script_path: "{{domain_name}}/scripts"

- name: "Setup vulnerabilities srv03"
  hosts: srv03
  roles:
  vars:
    script_path: "{{domain_name}}/scripts"
